// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoyalBureauShipping.Models;

#nullable disable

namespace RoyalBureauShipping.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230716134851_addShipOwner")]
    partial class addShipOwner
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoyalBureauShipping.Models.CargoShip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CargoShips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bulk Carrier"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Oil Tanker"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chemical Tanker"
                        },
                        new
                        {
                            Id = 4,
                            Name = " Gas Carrier"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cargo Ship other than any of the above"
                        });
                });

            modelBuilder.Entity("RoyalBureauShipping.Models.ShipModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Breadth")
                        .HasColumnType("int");

                    b.Property<int?>("CargoShipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CasualHistory")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CertificateValid")
                        .HasColumnType("datetime2");

                    b.Property<string>("Class_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassificationCharacters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CompletionDateSurvey")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateBuildingContract")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDelivery")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateofIssue")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeadweightShip")
                        .HasColumnType("int");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<string>("DistinctiveNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExemptionCertificate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FirstPostOutInspection")
                        .HasColumnType("datetime2");

                    b.Property<string>("GRT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrossTonnage")
                        .HasColumnType("int");

                    b.Property<string>("IMO_NO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssuedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Leangh")
                        .HasColumnType("int");

                    b.Property<string>("PermissibleMarineAreas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortSurvey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Port_Of_Register")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Propulsion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RevisionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SecondPostOutInspection")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShipAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeShipstrign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("RoyalBureauShipping.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "RoyalBureauShipping@admin.com",
                            FirstName = "Admin",
                            LastName = "Admin",
                            Password = "123456789"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
